### ISSUE TITLE
vagrant up fails: issue with matlab?

### ISSUE THREAD

**Issue by GladB** [srvk/DiViMe#128]
To update, I destroyed the VM, pulled the most recent version of the repo today and ran `vagrant up`. Instead of building the VM as it usually does, this time it gave me an error:

```
[...beginning of the installation...]
    default:     zlib:                     1.2.8-0           --> 1.2.11-0
    default:
    default: Proceed ([y]/n)?
    default: Invalid choice: exit
    default: Proceed ([y]/n)?
    default: Could not connect to https://repo.continuum.io/pkgs/free/linux-64/conda-env-2.6.0-0.tar.bz2
    default: Fetching packages ...
    default: Error: Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/linux-64/conda-env-2.6.0-0.tar.bz2
    default: su: User not known to the underlying authentication module
    default: Create python3 env
    default: /tmp/vagrant-shell: line 44: rm: command not found
    default: /tmp/vagrant-shell: line 70: cp: command not found
    default: /tmp/vagrant-shell: line 71: /bin/su: No such file or directory
    default: Download matlab installer
    default: /tmp/vagrant-shell: line 77: /usr/bin/wget: No such file or directory
    default: Install matlab
    default: /tmp/vagrant-shell: line 79: unzip: command not found
    default: /tmp/vagrant-shell: line 80: ./install: No such file or directory
    default: *******************************
    default:   matlab installation failed
    default: *******************************
    default: root@vagrant-ubuntu-trusty-64:/home/vagrant#
    default: exit
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I tried cloning a whole new version of the repo and doing the installation from scratch, and it just stopped at this for several hours before I killed the process:

```
[...beginning of the installation...]
scikit-learn-0 100% |###############################| Time: 0:00:00  11.84 MB/s
    default: #
    default: # To act
    default: ivate this environment, use:
    default: # > source activate divime
    default: #
    default: # To deactivate an active environment, use:
    default: # > source deactivate
    default: #
    default: Download matlab installer
```

Is there something that I am doing wrong/forgetting to do?
